/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cbattaru' at '3/18/16 7:52 PM' with Gradle 2.12
 *
 * @author cbattaru, @date 3/18/16 7:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
